#!/usr/bin/env node

var  yamq = require('../yamq/client.js');

var host;
var port;

if (process.argv.length >= 3)
    host = process.argv[2];
else
    host = "localhost";

if (process.argv.length >= 4)
    port = process.argv[3];
else
    port = 8124;

var stock = "";
var inbox = "";

if (process.argv.length >= 5) {
    stock = "stock_quotes_" + process.argv[4];
    inbox = "test_receive_myinbox_" + process.argv[4];
} else {
    stock = "stock_quotes";
    inbox = "test_receive_inbox";
}



var conn = yamq.make_connection(host,port);
var chan = yamq.make_channel(conn);
var outbox = yamq.make_inbox(chan,inbox,function(result) {
				  if (result.code == "ok") {
				      console.log("run...");
				  };
			     });

yamq.subscribe(chan,inbox,stock,function(){});
yamq.on_inbox(chan,inbox,function(msg) {
		  console.log(msg);
	      });
