#!/usr/bin/env node

var broker = require('./broker');
var port;

require('./debug').debug('mid');

if (process.argv.length >= 3)
   port = process.argv[2];
else
   port = 8124;
   
broker.run(port);

